---
apiVersion: v1
kind: Namespace
metadata:
  name: tbs-tekton
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: tbs-tekton
secrets:
  - name: my-registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-deploy-role
  namespace: tbs-tekton
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-sa:deploy-role
  namespace: tbs-tekton
roleRef:
  apiGroup: ""
  kind: Role
  name: pipeline-deploy-role
subjects:
- kind: ServiceAccount
  name: pipeline-sa
  namespace: tbs-tekton
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-sa:build-service-user-role
  namespace: tbs-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: build-service-user-role
subjects:
- kind: ServiceAccount
  name: pipeline-sa
  namespace: tbs-tekton
---
apiVersion: v1
data:
  default-service-account: pipeline-sa
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tbs-tekton
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default-service-account":"pipeline-sa"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"config-defaults","namespace":"tekton-pipelines"}}